# Generated by Django 3.2.5 on 2024-03-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='room_id',
        ),
    ]
