# Generated by Django 5.0.3 on 2024-04-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
