# Generated by Django 3.2.5 on 2023-10-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Doctor's registration number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialization'),
        ),
    ]
