# Generated by Django 3.2.5 on 2023-10-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231020_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_line_2',
        ),
    ]
