# Generated by Django 3.2.5 on 2023-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_specialization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
