# Generated by Django 3.2.5 on 2024-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_medicalrecord_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, upload_to='specialization'),
        ),
    ]
