# Generated by Django 3.2.5 on 2024-03-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240323_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
