# Generated by Django 3.2.5 on 2024-03-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_doctorprofile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
