# Generated by Django 3.2.5 on 2024-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20240324_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='city',
            new_name='clinic_city',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='country',
            new_name='clinic_country',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='state',
            new_name='clinic_state',
        ),
    ]
