# Generated by Django 5.0.3 on 2024-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
