# Generated by Django 5.0.3 on 2024-04-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_delete_order'),
        ('labs', '0002_pendinglabbooking'),
        ('orders', '0002_alter_order_doctor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='order',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.labtestbooking'),
        ),
    ]
